# Generated by Django 5.2.8 on 2025-12-01 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лицензии')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='realtors/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Риелтор',
                'verbose_name_plural': 'Риелторы',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('commercial', 'Коммерческая недвижимость'), ('land', 'Земельный участок')], max_length=20, verbose_name='Тип недвижимости')),
                ('status', models.CharField(choices=[('for_sale', 'Продажа'), ('for_rent', 'Аренда'), ('sold', 'Продано'), ('rented', 'Сдано в аренду')], default='for_sale', max_length=20, verbose_name='Статус')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (м²)')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='Количество спален')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='Количество ванных комнат')),
                ('main_image', models.ImageField(upload_to='properties/main/', verbose_name='Главное изображение')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Изображение 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='realty.client', verbose_name='Клиент')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='realty.realtor', verbose_name='Риелтор')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
    ]
